# Generated by Django 5.0 on 2023-12-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_team', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('owner_goals', models.IntegerField()),
                ('guest_goals', models.IntegerField()),
                ('is_over', models.BooleanField()),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='standings.team', to_field='id_team')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='standings.team', to_field='id_team')),
            ],
        ),
    ]
